### ISSUE TITLE
Some knobs fields stopped working

### ISSUE THREAD

**Issue by froseman-codex** [ookami-kb/storybook_flutter#68] opened 2022-01-19 11:22 UTC
Flutter stable 2.8.1

Cant select knobs parameters after update to 0.10.0. 
Example, options selector are inactive.
![image](https://user-images.githubusercontent.com/96050737/150118369-619174c0-810c-472e-b447-ee7999e10c86.png)

Another possibly related issue is when I change the text in textfield

<img src="https://user-images.githubusercontent.com/96050737/150118689-92efd076-8376-446b-82cb-d2f0257e78c7.png" width="200">

**Comment by ookami-kb** [comment] 2022-01-19 11:56
Hi,

Options selector should be fixed in `0.10.0+1`. Can you please check if it works for you?

Regarding textfield – I cannot reproduce it. Can you try it with the latest version and provide a reproducible example if it still happens?

**Comment by ookami-kb** [comment] 2022-02-03 16:18
Closing the issue, feel free to create a new one if the problem persists.

**Closed by ookami-kb** 2022-02-03 16:18 UTC
